name: foar
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - iopath
dependencies:
  - python=3.8
  - pytorch
  - pytorch-cuda
  - pytorch3d
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - ipykernel
  - jupyterlab
  - iopath
  - tqdm
  - open3d
  - opencv
  - easydict
  - einops
  - matplotlib
  - diffusers
  - huggingface_hub